// The pets you can choose. Their 3D models are built in pet3d.js from this data.
// `pitch` is how the pet replays your voice; `speech` is how it speaks its own lines.

export const PETS = [
  {
    id: 'cat',
    name: 'Miso',
    kind: 'Cat',
    emoji: '🐱',
    blurb: 'Squeaky and sassy',
    pitch: 1.6,
    speech: { pitch: 1.8, rate: 1.15 },
    food: '🐟',
    voice: { wave: 'sawtooth', pitch: 700 },
    colors: { fur: '#f29a2e', dark: '#c96a12', belly: '#fff1dc', limb: '#f29a2e', inner: '#ffb3bd', nose: '#e8707e' },
  },
  {
    id: 'dog',
    name: 'Biscuit',
    kind: 'Dog',
    emoji: '🐶',
    blurb: 'Loud and loyal',
    pitch: 1.25,
    speech: { pitch: 1.2, rate: 1.05 },
    food: '🦴',
    voice: { wave: 'square', pitch: 280 },
    colors: { fur: '#c98a52', dark: '#7a4a28', belly: '#f8e6cf', limb: '#c98a52', inner: '#7a4a28', nose: '#2b2020' },
  },
  {
    id: 'bunny',
    name: 'Clover',
    kind: 'Bunny',
    emoji: '🐰',
    blurb: 'Tiny chipmunk voice',
    pitch: 1.9,
    speech: { pitch: 2, rate: 1.25 },
    food: '🥕',
    voice: { wave: 'sine', pitch: 1100 },
    colors: { fur: '#f3ece4', dark: '#d9cdbf', belly: '#ffffff', limb: '#f3ece4', inner: '#f7a8ba', nose: '#f08fa3' },
  },
  {
    id: 'panda',
    name: 'Dumpling',
    kind: 'Panda',
    emoji: '🐼',
    blurb: 'Slow, deep rumble',
    pitch: 0.82,
    speech: { pitch: 0.4, rate: 0.85 },
    food: '🎋',
    voice: { wave: 'triangle', pitch: 200 },
    colors: { fur: '#f6f5f0', dark: '#2a2a30', belly: '#f6f5f0', limb: '#2a2a30', inner: '#2a2a30', nose: '#2a2a30' },
  },
  {
    id: 'fox',
    name: 'Rusty',
    kind: 'Fox',
    emoji: '🦊',
    blurb: 'Quick and cheeky',
    pitch: 1.45,
    speech: { pitch: 1.5, rate: 1.3 },
    food: '🍇',
    voice: { wave: 'sawtooth', pitch: 520 },
    colors: { fur: '#e8672a', dark: '#3a2a26', belly: '#fff3e6', limb: '#3a2a26', inner: '#3a2a26', nose: '#2b2020' },
  },
  {
    id: 'monkey',
    name: 'Coco',
    kind: 'Monkey',
    emoji: '🐵',
    blurb: 'Giggly and wild',
    pitch: 1.7,
    speech: { pitch: 1.7, rate: 1.2 },
    food: '🍌',
    voice: { wave: 'square', pitch: 600 },
    colors: { fur: '#8a5a3c', dark: '#5e3a24', belly: '#f1cfa6', limb: '#8a5a3c', inner: '#f1cfa6', nose: '#5e3a24' },
  },
  {
    id: 'penguin',
    name: 'Pebble',
    kind: 'Penguin',
    emoji: '🐧',
    blurb: 'Waddly and cool',
    pitch: 1.35,
    speech: { pitch: 1.35, rate: 1 },
    food: '🦐',
    voice: { wave: 'triangle', pitch: 450 },
    colors: { fur: '#2c3345', dark: '#1d2230', belly: '#ffffff', limb: '#2c3345', inner: '#2c3345', nose: '#ff9f1c', feet: '#ff9f1c' },
  },
  {
    id: 'unicorn',
    name: 'Sparkle',
    kind: 'Unicorn',
    emoji: '🦄',
    blurb: 'Magical and sweet',
    pitch: 1.75,
    speech: { pitch: 1.9, rate: 1.05 },
    food: '🍭',
    voice: { wave: 'sine', pitch: 900 },
    colors: { fur: '#fdf7ff', dark: '#ff8ad4', belly: '#ffffff', limb: '#fdf7ff', inner: '#ffc2e2', nose: '#f7a8c8', feet: '#c9a6f5' },
  },
];

export function findPet(id) {
  return PETS.find((pet) => pet.id === id) ?? PETS[0];
}
