// The pets you can choose. Their 3D models are built in pet3d.js from this data.
// `pitch` is how the pet replays your voice; `speech` is how it speaks its own lines.
// Both are kept gentle: funny, but always easy for a young child to understand.

export const PETS = [
  {
    id: 'cat',
    name: 'Miso',
    kind: 'Cat',
    emoji: '🐱',
    blurb: 'Squeaky and sassy',
    pitch: 1.4,
    speech: { pitch: 1.3, rate: 0.92 },
    food: '🐟',
    voice: { wave: 'sawtooth', pitch: 700 },
    colors: { fur: '#ff9a2b', dark: '#d9620b', belly: '#fff3e0', limb: '#ff9a2b', inner: '#ffb0bd', nose: '#f0647a', iris: '#3fae52' },
  },
  {
    id: 'dog',
    name: 'Biscuit',
    kind: 'Dog',
    emoji: '🐶',
    blurb: 'Loud and loyal',
    pitch: 1.2,
    speech: { pitch: 1.1, rate: 0.92 },
    food: '🦴',
    voice: { wave: 'square', pitch: 280 },
    colors: { fur: '#d8934c', dark: '#874a20', belly: '#fcead2', limb: '#d8934c', inner: '#874a20', nose: '#2a1d1b', iris: '#6a3d17' },
  },
  {
    id: 'bunny',
    name: 'Clover',
    kind: 'Bunny',
    emoji: '🐰',
    blurb: 'Light, squeaky voice',
    pitch: 1.5,
    speech: { pitch: 1.4, rate: 0.95 },
    food: '🥕',
    voice: { wave: 'sine', pitch: 1100 },
    colors: { fur: '#fbf5ee', dark: '#dccbb9', belly: '#ffffff', limb: '#fbf5ee', inner: '#ff9db5', nose: '#ff7b9a', iris: '#3d9be0' },
  },
  {
    id: 'panda',
    name: 'Dumpling',
    kind: 'Panda',
    emoji: '🐼',
    blurb: 'Slow, deep rumble',
    pitch: 0.88,
    speech: { pitch: 0.85, rate: 0.88 },
    food: '🎋',
    voice: { wave: 'triangle', pitch: 200 },
    colors: { fur: '#fafaf6', dark: '#25252b', belly: '#fafaf6', limb: '#25252b', inner: '#25252b', nose: '#25252b', iris: '#4a3222' },
  },
  {
    id: 'fox',
    name: 'Rusty',
    kind: 'Fox',
    emoji: '🦊',
    blurb: 'Quick and cheeky',
    pitch: 1.35,
    speech: { pitch: 1.25, rate: 0.95 },
    food: '🍇',
    voice: { wave: 'sawtooth', pitch: 520 },
    colors: { fur: '#ff6a26', dark: '#33211e', belly: '#fff6ec', limb: '#33211e', inner: '#33211e', nose: '#2a1d1b', iris: '#d08a12' },
  },
  {
    id: 'monkey',
    name: 'Coco',
    kind: 'Monkey',
    emoji: '🐵',
    blurb: 'Giggly and wild',
    pitch: 1.45,
    speech: { pitch: 1.35, rate: 0.95 },
    food: '🍌',
    voice: { wave: 'square', pitch: 600 },
    colors: { fur: '#9b5e35', dark: '#683a1f', belly: '#ffd8a6', limb: '#9b5e35', inner: '#ffd8a6', nose: '#683a1f', iris: '#6a3d17' },
  },
  {
    id: 'penguin',
    name: 'Pebble',
    kind: 'Penguin',
    emoji: '🐧',
    blurb: 'Waddly and cool',
    pitch: 1.3,
    speech: { pitch: 1.15, rate: 0.9 },
    food: '🦐',
    voice: { wave: 'triangle', pitch: 450 },
    colors: { fur: '#26314d', dark: '#182036', belly: '#ffffff', limb: '#26314d', inner: '#26314d', nose: '#ffab1f', feet: '#ffab1f', iris: '#2f77c4' },
  },
  {
    id: 'unicorn',
    name: 'Sparkle',
    kind: 'Unicorn',
    emoji: '🦄',
    blurb: 'Magical and sweet',
    pitch: 1.45,
    speech: { pitch: 1.4, rate: 0.9 },
    food: '🍭',
    voice: { wave: 'sine', pitch: 900 },
    colors: { fur: '#fff9ff', dark: '#ff79c9', belly: '#ffffff', limb: '#fff9ff', inner: '#ffbfe1', nose: '#ff97c8', feet: '#c598ff', iris: '#9457e6' },
  },
];

export function findPet(id) {
  return PETS.find((pet) => pet.id === id) ?? PETS[0];
}
